name: Upload Python Package

on:
  release:
    types: [published]
  pull_request:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: marian-code/python-lint-annotate@v3
      with:
        python-root-list: "src/ tests/*"  # accepts wildcards
        use-pycodestyle: false
        use-mypy: false
        use-vulture: true
        extra-pylint-options: "--output-format="colorized"
        python-version: "3.7"