name: Upload Python Package

on:
  release:
    types: [published]
  pull_request:
    branches:
      - "main"
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Generate requirements.txt file
        run: |
            touch requirements.txt
      - uses: marian-code/python-lint-annotate@v3
